// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Fdq6o6qBI1JKjK0vzGIRjz8c5pOTtzY',
    appId: '1:1021261635615:web:f595af8cba7ba085c8352a',
    messagingSenderId: '1021261635615',
    projectId: 'madelines-store',
    authDomain: 'madelines-store.firebaseapp.com',
    databaseURL: 'https://madelines-store-default-rtdb.firebaseio.com',
    storageBucket: 'madelines-store.firebasestorage.app',
    measurementId: 'G-WEHE1M9B4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs50HH4kbZIRbrlmQjTUdfImbp1u8nAGQ',
    appId: '1:1021261635615:android:be6576b3c59068b0c8352a',
    messagingSenderId: '1021261635615',
    projectId: 'madelines-store',
    databaseURL: 'https://madelines-store-default-rtdb.firebaseio.com',
    storageBucket: 'madelines-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdnUUawWzU6-SC0VBWku7-to0iycd2Hgo',
    appId: '1:1021261635615:ios:0a48484cc9c69875c8352a',
    messagingSenderId: '1021261635615',
    projectId: 'madelines-store',
    databaseURL: 'https://madelines-store-default-rtdb.firebaseio.com',
    storageBucket: 'madelines-store.firebasestorage.app',
    iosBundleId: 'com.example.myStoreAdminPane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdnUUawWzU6-SC0VBWku7-to0iycd2Hgo',
    appId: '1:1021261635615:ios:0a48484cc9c69875c8352a',
    messagingSenderId: '1021261635615',
    projectId: 'madelines-store',
    databaseURL: 'https://madelines-store-default-rtdb.firebaseio.com',
    storageBucket: 'madelines-store.firebasestorage.app',
    iosBundleId: 'com.example.myStoreAdminPane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Fdq6o6qBI1JKjK0vzGIRjz8c5pOTtzY',
    appId: '1:1021261635615:web:9a0662efab7b0472c8352a',
    messagingSenderId: '1021261635615',
    projectId: 'madelines-store',
    authDomain: 'madelines-store.firebaseapp.com',
    databaseURL: 'https://madelines-store-default-rtdb.firebaseio.com',
    storageBucket: 'madelines-store.firebasestorage.app',
    measurementId: 'G-VGXD99NM21',
  );
}
